model:
  arch: "NaiveCNN"
  kwargs:
    num_classes: 4

  loss:
    name: "Cross Entropy"
    id: "CE"

  metrics: ["accuracy", "precision", "recall", "f1"]

  optimizer:
    id: "adam"
    lr: 0.0005
    weight_decay: 0

  scheduler:
    id: null

trainer:
  gpus: 1
  accumulate_grad_batches: 1
  max_epochs: 100
  gradient_clip_val: 0
  precision: 32
  profiler: null
  auto_lr_find: false
  check_val_every_n_epoch: 1
  default_root_dir: "./"

  checkpoint:
    verbose: true
    dirpath: "./checkpoints"
    monitor: "accuracy"
    mode: "max"
    save_top_k: 3
    filename: "{arch}_{{epoch:02d}}_{{val_loss:.3f}}_{{accuracy:.2f}}"