arch: "NaiveCNN"

metrics:
  accuracy:
    kwargs:
      compute_on_step: false
  precision:
    kwargs:
      num_classes: 4
      average: "macro"
      compute_on_step: false
  recall:
    kwargs:
      num_classes: 4
      average: "macro"
      compute_on_step: false
  f1:
    args: [4]
    kwargs:
      average: "macro"
      compute_on_step: false

hparams:
  kwargs:
    num_classes: 4

  lr: 0.0005

  loss:
    name: "Cross Entropy"
    id: "CE"

  optimizer:
    id: "adam"
    weight_decay: 0

  scheduler:
    id: null

trainer:
  gpus: 1
  accumulate_grad_batches: 1
  max_epochs: 100
  gradient_clip_val: 0
  precision: 32
  profiler: null
  check_val_every_n_epoch: 1
  default_root_dir: "./"

  checkpoint:
    verbose: true
    dirpath: "./checkpoints"
    monitor: "metrics/accuracy"
    mode: "max"
    save_top_k: 3
    filename: "{arch}_{{epoch:02d}}_{{loss/val:.3f}}_{{metrics/accuracy:.2f}}"